// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220421185608_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Gender = "Female",
                            Name = "Rose",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Gender = "Female",
                            Name = "Doja",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Gender = "Female",
                            Name = "Elfreda",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            Gender = "Female",
                            Name = "Monah",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Gender = "Female",
                            Name = "Eiza",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 7,
                            Gender = "Male",
                            Name = "Norm",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 2,
                            Gender = "Male",
                            Name = "George",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 13,
                            Gender = "Male",
                            Name = "Vlad",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 3,
                            Gender = "Male",
                            Name = "Neuman",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 3,
                            Gender = "Male",
                            Name = "Addy",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
